#!/bin/bash

set -o pipefail
set -o nounset
set -o errexit

# Load "library" of common functionality
. @out@/share/emacs-server/common-lib

common_emacs_setup

setup_server_file_info

@out@/libexec/emacs-server/connect-emacs \
 "${emacs_server_name}" -e "$@"

common_emacs_cleanup
