#!/bin/bash

set -o pipefail
set -o nounset
set -o errexit

# Load "library" of common functionality
. @emacs-server@/share/emacs-server/common-lib

common_emacs_setup

setup_server_file_info

@emacs-server@/libexec/connect-emacs \
 "${emacs_server_name}" -e "$@"

common_emacs_cleanup
